theme: jekyll-theme-minimal
title: "Teaching Portfolio — Dipali Jain"
description: "Teaching philosophy, experience, evidence of effectiveness, mentoring, DEI, and recognition."
logo: /assets/headshot.png
url: "https://dipalijain.github.io"
baseurl: ""

show_downloads: false
author: Dipali Jain
github:
  is_project_page: false
  is_user_page: true
